var gtsMinList ={
    "jsList" : [
        "js/Global/Constant.js",
        "js/Global/Global.js",
        "js/project.js",
        "js/Pixi/MyPixi1.js",
        "js/html/HttpRequest.js",
        "js/Dialog/LoadingDialog.js",
        "js/Dialog/MiniGameLoadingDialog.js",
        "js/Dialog/MessageNode.js",
        "js/html/GameHotfix.js",
        "js/html/GameMng.js",
        "js/html/MyRequest.js",
        "js/html/Socket/LobbySocket.js",
        "js/html/LobbyRequest.js",
        "js/html/MiniGameRequest.js",
        "js/Socket/TopHuClient.js",
        "js/Socket/LobbyClient.js",
        "js/Socket/MiniGameClient.js",
        "js/Global/Cmd.js",
        "js/Global/Types.js",
        "js/Global/States.js",
        "js/Global/Utils.js",
        "js/Global/Helper.js",
        "js/ServerConfig/ServerConfig.js",
        "js/common/SuggestCardMng.js",
        "js/base/BaseGame.js",
        "js/base/BaseSlotGame.js",
        "js/slot/MainSlot.js",
        "js/ui/VirtualButton.js",
        "js/ui/ToggleNodeGroup.js",
        "js/ui/NewAction.js",
        "js/ui/Card.js",
        "js/ui/Chip.js",
        "js/ui/ChipTo.js",
        "js/ui/XocDiaUi.js",
        "js/ui/PhomUi.js",
        "js/ui/UserAvatar.js",
        "js/ui/MyDialog.js",
        "js/ui/ProgressBar.js",
        "js/ui/MaskLayer.js",
        "js/ui/GamePlayer.js",
        "js/ui/MauBinhUi.js",
        "js/ui/Narrative.js",
        "js/ui/TurnButtonUI.js",
        "js/ui/LiengUi.js",
        "js/ui/SoundName.js",
        "js/ui/ChanUi.js",
        "js/ui/ChiaBai.js",
        "js/ui/CardChan.js",
        "js/ui/CardEarnNode.js",
        "js/ui/ResultTable.js",
        "js/ui/XuongUdialog.js",
        "js/Dialog/UserDialog.js",
        "js/view/LoadingScene.js",
        "js/view/GameTopBar.js",
        "js/view/Main.js",
        "js/view/GameFactory.js",
        "js/view/GameScene.js",
        "js/view/GameXocDia.js",
        "js/view/GamePhom.js",
        "js/view/GameMauBinh.js",
        "js/view/GameTLMN.js",
        "js/view/GameSam.js",
        "js/view/GameLieng.js",
        "js/view/GameXiTo.js",
        "js/view/GamePoker.js",
        "js/view/GameBaCay.js",
        "js/view/GameChan.js",
        "js/Social/MyFb.js",
        "js/htmlDialog/TopHu.js"
    ],
    "mh": [
        "js/htmlDialog/chatLayer.js",
        "js/htmlDialog/mhLibs.js",
        "js/htmlDialog/slider.js",
        "js/htmlDialog/mhTimer.js" ,
        "js/htmlDialog/mhPopup.js" ,
        "js/htmlDialog/menuMiniGame.js" ,
        "js/htmlDialog/MiniPoker.js" ,
        "js/slot/Candy.js" ,
        "js/slot/DiceDice.js" ,
        "js/slot/DeadOrAlive.js" ,
        "js/slot/GoldenMonkey.js" ,
        "js/htmlDialog/TrungPhucSinh.js" ,
        "js/htmlDialog/TaiXiu.js" ,
        "js/htmlDialog/ThienDia.js" ,
        "js/htmlDialog/SieuXe.js" ,
        "js/htmlDialog/BauCua.js" ,
        "js/htmlDialog/CaoThap.js" ,
        "js/htmlDialog/mhApp.js",
        "js/Plugin/PhatLocPlugin.js",
        "js/Plugin/CaoThapPlugin.js",
        "js/Plugin/VongQuayPlugin.js",
        "js/Plugin/BauCuaPlugin.js",
        "js/Plugin/ThienDiaPlugin.js",
        "js/Plugin/OtpPlugin.js",
        "js/Plugin/JackpotCardPlugin.js",
        "js/htmlDialog/LobbyAnimation.js" 
    ],
    "List":[
        "jsList:game.min.js",
        "mh:mh.min.js"
    ]

}



